version: "3.8"

services:
  app:
    build: .
    container_name: realestate-app
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: ds-2025
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d4nij3h5pdvs73cn7ri0-a.frankfurt-postgres.render.com:5432/dsdb_x568
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: iP7KK4xhIUFD0ZSUntYCMRmYf2z6BzNU
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
